/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface People {
  "id"?: string 
  "name"?: string | null 
  "category"?: string | null 
  "famous_as"?: string | null 
  "birthdate"?: string | null 
  "birthplace"?: string | null 
  "died"?: string | null 
  "notes"?: string | null 
}
export interface People2 {
  "id"?: string | null 
  "name"?: string | null 
  "years"?: string | null 
  "description"?: string | null 
  "alive"?: boolean | null 
}
